#!/usr/bin/python3
import argparse
import sys
import os

def setupArgs():
    
    def dir_path(path):
        if os.path.isdir(path):
            return path
        else:
            raise argparse.ArgumentTypeError(f"{path} is not a valid directory")

    parser = argparse.ArgumentParser()
    parser.add_argument("-s", "--snap-location", type = dir_path, default = "/snaps", help = "where snaps are located")
    parser.add_argument("action", choices = ["log", "create", "delete"], help = "choose action")
    return parser.parse_args()

def showLog(log_file):
    if os.path.isfile(log_file):
        with open(log_file, 'r') as log:
            print(log.read())

if __name__ == "__main__":
    args = setupArgs()

    if args.action == "log":
        showLog(args.snap_location + "/snaps.log")